// generated by Fast Light User Interface Designer (fluid) version 1.0308

#ifndef x86internals_h
#define x86internals_h
#include <FL/Fl.H>
#include "types.h"
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Input.H>
#include <FL/Fl_Button.H>
extern void Button_CB(Fl_Button*, void*);
#include <FL/Fl_Text_Display.H>

class X86Internals {
public:
  Fl_Double_Window* make_main_window();
  Fl_Input *hex_input;
  Fl_Text_Display *internal_struct;
};
#endif
