// generated by Fast Light User Interface Designer (fluid) version 1.0308

#include "x86internals.h"

Fl_Double_Window* X86Internals::make_main_window() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(1040, 720);
    w = o; if (w) {/* empty */}
    o->user_data((void*)(this));
    { hex_input = new Fl_Input(230, 497, 180, 28, "HexInput");
    } // Fl_Input* hex_input
    { Fl_Button* o = new Fl_Button(420, 495, 70, 30, "Submit");
      o->callback((Fl_Callback*)Button_CB);
    } // Fl_Button* o
    { internal_struct = new Fl_Text_Display(25, 35, 990, 430, "Global Descriptor Table");
    } // Fl_Text_Display* internal_struct
    o->end();
  } // Fl_Double_Window* o
  return w;
}
